http:
  host: '0.0.0.0'
  port: 5000
  debug: false

trusted_authority:
  re_encryption:
    triggers:
      read: true
      write: true
    scheduling:
      lazy: true
      lastAccessTimeOffset: 0 # In seconds
  encryption_engine:
    blockSize: 32
    logPerformance: false
