http:
  host: '0.0.0.0'
  port: 5000
  debug: false

trusted_authority:
  re_encryption:
    triggers:
      read: true
      write: true
    scheduling:
      lazy: false
      lastAccessTimeOffset: 300 # In seconds
  encryption_engine:
    blockSize: $BLOCK_SIZE
    logPerformance: false
