http:
  host: '0.0.0.0'
  port: 5000
  debug: false

re_encryption:
  triggers:
    read: true
    write: true
  scheduling:
    lazy: false
    lastAccessTimeOffset: 300 # In seconds
  blockSize: 32
  logPerformance: false